### ISSUE TITLE
setPostCondition stuck in infinite loop

### ISSUE THREAD

**Issue by surecloud-malokaidi** [naver/fixture-monkey#989] opened 2024-06-13 11:26 UTC
## Describe the bug
When using `setPostCondition` to select a subset acceptable subclasses the generator seems to get stuck in infinite loop if the predicate evaluates to `false` on the class type

## Your environment
* version of Fixture Monkey: 10.18
* version of Java/Kotlin: Java 21

## Steps to reproduce
Run `FixtureMonkeyTest.java` from https://github.com/surecloud-malokaidi/fixture-monkey-bug

## Expected behaviour
I would expect FixtureMonkey to generate a different type of class if the predicate evaluates to false

## Actual behaviour
The same class type is used and only it's attributes values change each time the predicate is false resulting in an infinite number of attempts (maxing out at max tries) at creating an object satisfying the condition.

**Comment by seongahjo** [comment] 2024-06-14 05:30
@surecloud-malokaidi 
Hello.

Sorry, currently Fixture Monkey does not support `setPostCondition` to filter subclasses.

The features related to subclasses are planned to be supported since `1.1.x`. It would be two parts.
1. Add new ArbitraryBuilder API `interfaceImplements`, `abstractExtends` (the name is same as the option in FixtureMonkeyBuilder)
2. Extend the existing API (For example, `setPostCondition`) to support subclasses


In 1.0.x you should use `set` API to set subclasses instead.

Thank you.

**Comment by seongahjo** [comment] 2024-08-02 03:02
@surecloud-malokaidi 
Hi, thanks for waiting. The problem is fixed in 1.0.22.

Please let me know if you experience any further problems.

Thank you very much.

**Comment by seongahjo** [comment] 2024-08-31 06:29
The issue is closed as it has been fixed since 1.0.22.
If you have any problems, please reopen the issue.

**Closed by seongahjo** 2024-08-31 06:29 UTC
Labels: bug
