### ISSUE TITLE
Arbitrary always return same value in specific case

### ISSUE THREAD

**Issue by dbgsprw** [naver/fixture-monkey#667] opened 2023-06-13 02:18 UTC
## Describe the bug
Arbitrary always return same value in specific case. Refer to the code below.

## Your environment
* version of Fixture Monkey
0.5.6
* version of Java/Kotlin
zulu-17, 1.7.22

###
```kt
class FixtureMonkeyTest {
    data class Foo(
        val barList: List<Bar>,
    )

    data class Bar(val baz: Baz)

    data class Baz(val id: String, val name: Int)

    class CustomBuilderGroup {
        fun listSize(fixture: FixtureMonkey): ArbitraryBuilder<Foo> =
            fixture.giveMeBuilder<Foo>()
                .size("barList", 3)

        fun id(fixture: FixtureMonkey): ArbitraryBuilder<Baz> =
            fixture.giveMeBuilder<Baz>()
                .setExp(Baz::id, Arbitraries.strings().numeric().ofLength(10))
    }

    @Test
    fun test() {
        val fixture = FixtureMonkey
            .builder()
            .plugin(KotlinPlugin())
            .registerGroup(CustomBuilderGroup::class.java)
            .build()
            .giveMe<Foo>(3)

        val idSet = fixture
            .flatMap { it.barList }
            .map {
                println("id=${it.baz.id} name=${it.baz.name}")
                it
            }
            .map { it.baz.id }
            .toSet()

        Assertions.assertThat(idSet).hasSize(9)
    }
}
```
```
id=4323847538 name=24
id=4323847538 name=48
id=4323847538 name=-509965389
id=4323847538 name=-75
id=4323847538 name=-3582138
id=4323847538 name=-7
id=4323847538 name=797
id=4323847538 name=-38
id=4323847538 name=-2008

java.lang.AssertionError: 
Expected size: 9 but was: 1 in:
["7110474456"]
```

## Expected behaviour
Generate random string

## Actual behaviour
Generate same string

**Comment by seongahjo** [comment] 2023-06-13 06:11
@dbgsprw 
It is a bug. It'll be fixed in 0.5.8.

You could prevent this bug by using `setNotNull` as a quick fix. 

```kotlin
 fun listSize(fixture: FixtureMonkey): ArbitraryBuilder<Foo> =
            fixture.giveMeBuilder<Foo>()
                .size("barList", 3)
                .setNotNull("barList[*]")
```

**Comment by seongahjo** [comment] 2023-06-27 04:41
@dbgsprw 
The issue is closed because It is fixed in 0.5.8. 
If it is not fixed, please reopen the issue.

**Closed by seongahjo** 2023-06-27 04:41 UTC
Labels: bug
